### ISSUE TITLE
Some questions ...or issues?

### ISSUE THREAD

**Issue by bukazoltan** [tegon/traktflix#1]
Hello! I've tried using your plugin, it's great that finally we have something like that, so I'm very greatful. But for some reason my checkin doesn't seem to work? Is it scrobbles only at the end of the episode as a "watched"? Could it be possible to make it check in as I start watching the episode or it should already do that just bugging for me? It's not quite clear from the documentation for me.

**Comment by tegon** [comment]
It uses scrobble method from Trakt, so you have to watch till 80% to became "watched" in your trakt history. The checkin is actually another method, it sets the episode to watched right the way, but it is not implemented in this plugin. Personally, I prefer the scrobble, because if you pause for some reason, it will not set the episode as watched.

**Comment by bukazoltan** [comment]
Oh I understand! Thank you for the quick answer! I got used to checkin, maybe an option to choose in a later version? That would be great. Anyway, great plugin, I appreciate it greatly!

**Comment by tegon** [comment]
Thanks! I use checkin too, but I think an app like SeriesGuide is more appropriate for the job, but if more users find this needed, sure we can thought for the future. Thanks again.
