### ISSUE TITLE
Firefox Extensions doesn't open

### ISSUE THREAD

**Issue by RainerZufahl** [tegon/traktflix#125]
Hello,

on Firefox 71.0 with traktflix 2.1.0, after installing there is no extension icon anywhere. It does appear in the list of installed extensions, but there is no way to actually open it to sign into Trakt.tv. 

I tried getting any more information about why this is happening, but as I didn't really know where to look that didn't get me very far. All I can say is that the newest version for Chrome seems to work (there is an icon and I can open the menu).

I'm aware that this isn't very helpful with this little information, but I'll happily supply more info if needed.

**Comment by chrisofspades** [comment]
I have the icon, but when I click it the button to view my history is gone. This is in both Firefox and Chrome.

**Comment by rafaelgssa** [comment]
@chrisofspades If you can see the options button, a workaround could be to go to the options page and clear the storage (see #112).

I believe the history button not appearing could be related to Trakt tokens expiring, because the extension doesn't currently deal with that. But I don't know what could make the extension button not even appear, I'll have to look further into that.

**Comment by chrisofspades** [comment]
Clearing the storage did the trick, thanks. It's strange that uninstalling
and reinstalling didn't work for though.

**Comment by rafaelgssa** [comment]
This should be fixed in v2.1.1. Let me know if not.
