### ISSUE TITLE
Works with chromecast?

### ISSUE THREAD

**Issue by samukets** [tegon/traktflix#23]
Works with chromecast?

**Comment by tegon** [comment]
It should work, are you having issues?

**Comment by samukets** [comment]
yes but i guess is because my language is pt-br...

**Comment by tegon** [comment]
It could be since the only language supported is USA English. What kind of issues are you having?

**Comment by samukets** [comment]
do not mark as watched, i guess is because the language pt-br, lets wait for updates to try use de plugin again....

**Comment by tegon** [comment]
The language can cause some issues:
- The movie/episode couldn't be found on Trakt by the title, so it will not track anything.
- The results from search are wrong because of the title, and it will track the wrong movie/episode.

I'll test again today with the chromecast, but the support for other languages is not being developed yet, is on the plans for the future.

**Comment by tegon** [comment]
Found a issue when finding the progress with chromecast mode. Trakt needs the progress to be at least 80% to mark the item as watched. I'll release an update with a fix later today.

**Comment by tegon** [comment]
Fixed on v1.0.5.5.
