### ISSUE TITLE
Wrong check-in on remake of a movie

### ISSUE THREAD

**Issue by athosbr99** [tegon/traktflix#29]
I started to watch Ocean's Eleven (the one with Clooney http://www.netflix.com/watch/60021783 - https://trakt.tv/movies/ocean-s-eleven-2001)  and Traktflix made the check-in on the original one (https://trakt.tv/movies/ocean-s-eleven-1960)

I'm using Netflix on Brazil with Portuguese-Brazil language.

**Comment by tegon** [comment]
How is the movie title appearing in your Netflix player?

**Comment by athosbr99** [comment]
It is "Onze homens e um segredo", the movie title in portuguese.

I've watched other movies and series and it works fine with them.

**Comment by tegon** [comment]
Yep, I've noticed that. It is weird, but for some queries the trakt search can handle localization, for others it can't. That's why I say English is the only language supported - this is what the trakt API says too.
I get the first search result, you can see the difference right from trakt:

https://trakt.tv/search/movies?utf8=%E2%9C%93&query=Ocean%27s+Eleven
https://trakt.tv/search/movies?utf8=%E2%9C%93&query=Onze+homens+e+um+segredo

I'm planning to do search using the current locale and year, but it will take some time to be finished.
