### ISSUE TITLE
History sync not saving

### ISSUE THREAD

**Issue by Electronic87** [tegon/traktflix#39]
Went into history from Netflix - clicked 100 item toggles (made the toggle red) and then hit sync - Popup with x items synced shows up. Closed tab  I refreshed Netflix, reopened trakt history - not saved (toggles grey on same episodes).

I attempted a second time about the same amount of items hit sync, closed and reopened not saved.

Finally tried one item thinking the issue might be I'm trying to sync to many things, hit sync - none of my items are red anymore all grey. I closed and reopened history in trakt a few times to refresh. Still all grey toggles.

Apologies if I'm doing something wrong.

Thanks for the hard work.

**Comment by KaiStarkk** [comment]
Having the same issue. I think the logic of this functionality is poorly thought out, it still isn't clear what the toggle actually means.

My suggestion would be, per episode:
- a label for the toggle with "Keep synced"
- a button "Sync once"
- an icon showing a tick if the time on Netflix and Trakt are the same, or a cross if they are different

**Comment by tegon** [comment]
That's right, the toggle is gray when the item is found on your Trakt history. This extension doesn't keep any data locally, so every time you got to the history sync, the data is fetched again, and you can sync those items you want.
This leaves more control to you, because some times an movie or episode couldn't be found on Trakt search - this you leave it in gray - and you may want to sync it manually, some users asked for this.
I'll probably add a page explaining these features and how to use the sync. If you know how it works, you can avoid those duplicates pretty easily.
Sorry for the misunderstanding. If you have any more questions, please send here.
