### ISSUE TITLE
Doesn't identify the episodes

### ISSUE THREAD

**Issue by Skaronator** [tegon/traktflix#44]
Seems like it only recognizes some episodes not all. For example it only identify the "Ching Chong Chang" but not the other.

![image](https://cloud.githubusercontent.com/assets/2886913/22250451/3309ec56-e247-11e6-8441-d651e68b0e2b.png)

Probably because its german? I can't do much on the netflix settings page since my subscription run out.

**Comment by tegon** [comment]
Yep, the history sync only works with English. That's because the [Netflix history page](https://www.netflix.com/WiViewingActivity) doesn't include the episode number. So I have to get a list with all the episodes of that season and compare their title. As you can see, the title of "Ching Chong Chang" is exactly the same, so everything works fine.

**Comment by Skaronator** [comment]
Is it possible to switch the netflix page to english?

**Comment by tegon** [comment]
Yes, you can go to https://www.netflix.com/LanguagePreferences and change it to English.

**Comment by Skaronator** [comment]
Doesn't work without subscription... probably going to renew it for a month.

Thanks for the quick response.

**Comment by Skaronator** [comment]
Update: Worked!

**Comment by tegon** [comment]
Great! Glad that it worked out 😄
