### ISSUE TITLE
Traktflix stopped scrobbling

### ISSUE THREAD

**Issue by sangohandbz** [tegon/traktflix#71]
Hello,

Since a few weeks traktflix stoped scrobbling and does not mark the episodes as viewed.
My local history is up to date which is weird, so I hve to sync manually.

Using chrome under Linux.
Edit : Traktflix 1.0.8.3. Debian 9 & Fedora 26

**Comment by TakerMc** [comment]
Hello,

I have exactly the same issue ! I'm using also linux (ubuntu). 

I've tried a few things, I've reinstall chrome completely and traktflix but it's still doesn't scrobble

**Comment by padok** [comment]
Hey,
I can also confirm that.

Traktflix:  1.0.8.3
OS: Linux, Ubuntu 17.10

The history works, but it no longer recognizes when something is played. The icon does not turn red.

**Comment by tegon** [comment]
Sorry for taking so long, things have been really crazy lately. I'll try to tackle this tonight.

**Comment by tegon** [comment]
I just tested here and it worked. It may be a problem with chrome for Ubuntu, since I use macOS.
The bad news is that I don't have access to an Ubuntu machine to figure out what's happing here :/

**Comment by cobrabr** [comment]
I'm running Windows and mine stops scrobbling ever so often (I can't even open the little popup that we get when on the Netflix site). I have to reinstall the extension to be able to scrobble again -- otherwise, I have to go to the Sync History (which I had to bookmark, since the popup doesn't work, like I mentioned above) page and manually sync.

**Comment by sangohandbz** [comment]
Problem has been solved on my side.
It probably was a problem with the chrome build for Linux
