### ISSUE TITLE
Trying to login to Trakt gives oAuth error

### ISSUE THREAD

**Issue by joaociocca** [tegon/traktflix#90]
On 2.0.6, manually installed on Chrome/Vivaldi, when I try to login with Trakt I get Trakt's popup with oAuth error, "The requested redirect uri is malformed or doesn't match client redirect URI."

**Comment by deepfriedmind** [comment]
Same issue here. Can't log in to Trakt, hence can't use the extension.

**Comment by jochemdu** [comment]
Yes i got the same issue when signing into trakt with Facebook.

Chrome: 71.0.3578.98 (Officiële build) (64-bits)
Traktflix: 2.0.6

**Comment by gsrafael01** [comment]
Sorry for the late response, I didn't see this. v2.0.6 does not authenticate when manually installed, because the OAuth uses the extension URI, and when you manually install an extension, it has a dynamic URI. The only URIs authorized by my application are:

* https://022dad2a5ccca7cb936044240b2e43d58925dddd.extensions.allizom.org/
* https://ehlckfimahifadnbecobagimllmbdmde.chromiumapp.org/

Which are the static URIs for the [Firefox](https://addons.mozilla.org/en-US/firefox/addon/traktflix/) and the [Chrome](https://chrome.google.com/webstore/detail/traktflix/ehlckfimahifadnbecobagimllmbdmde/related) (currently unlisted - [more info](https://github.com/tegon/traktflix/issues/86#issuecomment-451347213)) versions.

**Comment by joaociocca** [comment]
> So if you want to use the extension manually, you'll have to deploy your own Trakt application and build your own extension. Otherwise, you can just use the unlisted Chrome version until @tegon restores the extension.

I pretty ignorant about how this is done, and currently lacking time to research and actually learn, you've got a tutorial we can follow somewhere?

**Comment by gsrafael01** [comment]
v2.0.7 allows authenticating when manually installed, so closing this.
